# Generated by Django 3.1.14 on 2025-12-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#3b82f6', 'Blue'), ('#10b981', 'Green'), ('#f59e0b', 'Amber'), ('#ef4444', 'Red'), ('#8b5cf6', 'Purple'), ('#ec4899', 'Pink'), ('#6b7280', 'Gray'), ('#14b8a6', 'Teal')], default='#3b82f6', max_length=7),
        ),
    ]
