# Generated by Django 3.1.14 on 2025-12-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extension_number', models.CharField(max_length=20, verbose_name='Extension Number')),
                ('full_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Number')),
            ],
        ),
    ]
