# Generated by Django 3.1.14 on 2025-12-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential_manager', '0002_auto_20251217_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='description',
            field=models.CharField(default='No Description', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='ipv4',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IPv4'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
